### PR TITLE
Add support for Pika

### PR DESCRIPTION
**Pull request by luismiramirez**
Add instrumentation support for Pika messages. The global messaging extractor already covers the cases this instrumentation adds, so there's no need for a specific extractor so far.

Action with message production:

image

Consumption action automatically instrumented

image

Part of: #181

### CODE REVIEW

**Comment by luismiramirez** [comment]
Docs: https://github.com/appsignal/appsignal-docs/pull/1937

**Review by tombruijn — APPROVED** [review]

**Comment by unflxw** [comment]
The instrumentation does some wacky stuff here that our global extractor is not ready to handle. I think it would be good to add a custom extractor in the agent to fix this.

---

There are two spans here, one for sending the span and another for receiving it, that the Pika instrumentation for Python, in the test setup, sends with the names "test send" and "test receive".

These are actually pretty great span names! They are low cardinality, and they refer to the something that is meaningful to the user (the queue name, in this case "test") and a clear action ("send", "receive")

But then, **because the attributes are not correctly set, the global extractor does not know what to do with them**, and it messes them up in different ways.

For the send span, because there is no `messaging.operation` value (it should be "publish") the global extractor mostly doesn't know what to do with it. It does not set a good category (something like "send.rabbitmq" or "publish.rabbitmq", instead of "unknown.rabbitmq") and it does not change the name (this is actually good)

For the receive span, the opposite happens. Because there is a `messaging.operation` value ("receive") the global extractor sets the category (good) and rewrites the name.

But, when it rewrites the name, because `messaging.destination` is set to the customer tag (an opaque, high-cardinality value) instead of to the queue name ("test"), it messes it up, and rewrites it as something like "receive message (ctag.68b329da9893e34099c7d8ad5cb9c940)", which is less useful for the user than the queue name.

---

Thankfully this is why we have extractors! I would suggest a very simple extractor that doesn't use the messaging global extractor at all, instead just leaving the span name as-is, and setting the category using the last word of the span name (so, "send.pika", or "receive.pika"). Does that sound reasonable?

**Comment by unflxw** [comment]
Ah, the agent is also merging the trace for the consumer and the producer (because they are propagated as the same trace)

Ideally, these would be two separate traces, like in Sidekiq, Celery or BullMQ. But this is harder to fix, so maybe we can leave it like this for now.

**Comment by luismiramirez** [comment]
thanks for the insight @unflxw, I'll work on an extractor

**Pull request merged**
